### ISSUE TITLE
Use constants?

### ISSUE THREAD

**Issue by bonnyr** [weberr13/go-reducers#2]
Use constants for this. You may also want to do something like:
t = max(minThreads, min(t, maxThreads))

https://github.com/weberr13/go-reducers/blob/31d27f052ed342d46dcdb051fc36fcacb7d52236/mapping/mapping.go#L31-#L36

**Comment by weberr13** [comment]
@bonnyr  please review the linked MR above and see if that is what you had in mind

**Comment by bonnyr** [comment]
@weberr13 - regarding the numWorkers thing - yes, thanks!
